# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lady = Category.create(category: "レディース")
lady_1 = lady.children.create(category: "トップス")
lady_1.children.create([{category: "Tシャツ/カットソー(半袖/袖なし)"},{category: "Tシャツ/カットソー(七分/長袖)"},{category: "シャツ/ブラウス(半袖/袖なし)"},{category: "シャツ/ブラウス(七分/長袖)"},{category: "ポロシャツ"},{category: "キャミソール"},{category: "タンクトップ"},{category: "ホルターネック"},{category: "ニット/セーター"},{category: "チュニック"},{category: "カーディガン/ボレロ"},{category: "アンサンブル"},{category: "ベスト/ジレ"},{category: "パーカー"},{category: "トレーナー/スウェット"},{category: "ベアトップ/チューブトップ"},{category: "ジャージ"},{category: "その他"}])
lady_2 = lady.children.create(category: "ジャケット/アウター")
lady_2.children.create([{category: "テーラードジャケット"},{category: "Gジャン/デニムジャケット"},{category: "レザージャケット"},{category: "ダウンジャケット"},{category: "ライダースジャケット"},{category: "ミリタリージャケット"},{category: "ダウンベスト"},{category: "ジャンパー/ブルゾン"},{category: "ポンチョ"},{category: "ロングコート"},{category: "トレンチコート"},{category: "ダッフルコート"},{category: "ピーコート"},{category: "チェスターコート"},{category: "モッズコート"},{category: "スタジャン"},{category: "毛皮/ファーコート"},{category: "スプリングコート"},{category: "スカジャン"},{category: "その他"}])

lady_3 = lady.children.create(category: "パンツ")
lady_3.children.create([{category: "デニム/ジーンズ"},{category: "ショートパンツ"},{category: "カジュアルパンツ"},{category: "ハーフパンツ"},{category: "チノパン"},{category: "ワークパンツ/カーゴパンツ"},{category: "クロップドパンツ"},{category: "サロペット/オーバーオール"},{category: "オールインワン"},{category: "サルエルパンツ"},{category: "ガウチョパンツ"},{category: "その他"}])
lady_4 = lady.children.create(category: "スカート")
lady_4.children.create([{category: "ミニスカート"},{category: "ひざ丈スカート"},{category: "ロングスカート"},{category: "キュロット"},{category: "その他"}])
lady_5 = lady.children.create(category: "ワンピース")
lady_5.children.create([{category: "ミニワンピース"},{category: "ひざ丈ワンピース"},{category: "ロングワンピース"},{category: "その他"}])
lady_6 = lady.children.create(category: "靴")
lady_6.children.create([{category: "ハイヒール/パンプス"},{category: "ブーツ"},{category: "サンダル"},{category: "スニーカー"},{category: "ミュール"},{category: "モカシン"},{category: "ローファー/革靴"},{category: "フラットシューズ/バレエシューズ"},{category: "長靴/レインシューズ"},{category: "その他"}])
lady_7 = lady.children.create(category: "ルームウェア/パジャマ")
lady_7.children.create([{category: "パジャマ"},{category: "ルームウェア"}])
lady_8 = lady.children.create(category: "レッグウェア")
lady_8.children.create([{category: "ソックス"},{category: "スパッツ/レギンス"},{category: "ストッキング/タイツ"},{category: "レッグウォーマー"},{category: "その他"}])
lady_9 = lady.children.create(category: "帽子")
lady_9.children.create([{category: "ニットキャップ/ビーニー"},{category: "ハット"},{category: "ハンチング/ベレー帽"},{category: "キャップ"},{category: "キャスケット"},{category: "麦わら帽子"},{category: "その他"}])

lady_10 = lady.children.create(category: "バッグ")
lady_10.children.create([{category: "ハンドバッグ"},{category: "トートバッグ"},{category: "エコバッグ"},{category: "リュック/バックパック"},{category: "ボストンバッグ"},{category: "スポーツバッグ"},{category: "ショルダーバッグ"},{category: "クラッチバッグ"},{category: "ポーチ/バニティ"},{category: "ボディバッグ/ウェストバッグ"},{category: "マザーズバッグ"},{category: "メッセンジャーバッグ"},{category: "ビジネスバッグ"},{category: "旅行用バッグ/キャリーバッグ"},{category: "ショップ袋"},{category: "和装用バッグ"},{category: "かごバッグ"},{category: "その他"}])
lady_11 = lady.children.create(category: "アクセサリー")
lady_11.children.create([{category: "ネックレス"},{category: "ブレスレット"},{category: "バングル/リストバンド"},{category: "リング"},{category: "ピアス(片耳用)"},{category: "ピアス(両耳用)"},{category: "イヤリング"},{category: "アンクレット"},{category: "ブローチ/コサージュ"},{category: "チャーム"},{category: "その他"}])

lady_12 = lady.children.create(category: "ヘアアクセサリー")
lady_12.children.create([{category: "ヘアゴム/シュシュ"},{category: "ヘアバンド/カチューシャ"},{category: "ヘアピン"},{category: "その他"}])
lady_13 = lady.children.create(category: "小物")
lady_13.children.create([{category: "長財布"},{category: "折り財布"},{category: "コインケース/小銭入れ"},{category: "名刺入れ/定期入れ"},{category: "キーケース"},{category: "キーホルダー"},{category: "手袋/アームカバー"},{category: "ハンカチ"},{category: "マフラー/ショール"},{category: "ストール/スヌード"},{category: "バンダナ/スカーフ"},{category: "ネックウォーマー"},{category: "サスペンダー/ベルト"},{category: "サングラス/メガネ"},{category: "手帳"},{category: "傘"},{category: "レインコート/ポンチョ"},{category: "ミラー"},{category: "タバコグッズ"},{category: "その他"}])
lady_14 = lady.children.create(category: "時計")
lady_14.children.create([{category: "腕時計(アナログ)"},{category: "腕時計(デジタル)"},{category: "ラバーベルト"},{category: "レザーベルト"},{category: "金属ベルト"},{category: "その他"}])
lady_15 = lady.children.create(category: "ウィッグ/エクステ")
lady_15.children.create([{category: "前髪ウィッグ"},{category: "ロングストレート"},{category: "ロングカール"},{category: "ショートストレート"},{category: "ショートカール"},{category: "その他"}])

lady_16 = lady.children.create(category: "浴衣/水着")
lady_16.children.create([{category: "浴衣"},{category: "着物"},{category: "振袖"},{category: "長襦袢/半襦袢"},{category: "水着セパレート"},{category: "水着ワンピース"},{category: "水着スポーツ用"},{category: "その他"}])

lady_17 = lady.children.create(category: "スーツ/フォーマル/ドレス")
lady_17.children.create([{category: "スカートスーツ上下"},{category: "パンツスーツ上下"},{category: "ドレス"},{category: "パーティーバッグ"},{category: "シューズ"},{category: "ウェディング"},{category: "その他"}])
lady_18 = lady.children.create(category: "マタニティ")
lady_18.children.create([{category: "トップス"},{category: "アウター"},{category: "インナー"},{category: "ワンピース"},{category: "パンツ/スパッツ"},{category: "スカート"},{category: "パジャマ"},{category: "授乳服"},{category: "その他"}])
lady_19 = lady.children.create(category: "その他")
lady_19.children.create([{category: "コスプレ"},{category: "下着"},{category: "その他"}])

men = Category.create(category: "メンズ")
men_1 = men.children.create(category: "トップス")
men_1.children.create([{category: "Tシャツ/カットソー(半袖/袖なし)"},{category: "Tシャツ/カットソー(七分/長袖)"},{category: "シャツ"},{category: "ポロシャツ"},{category: "タンクトップ"},{category: "ニット/セーター"},{category: "パーカー"},{category: "カーディガン"},{category: "スウェット"},{category: "ジャージ"},{category: "ベスト"},{category: "その他"}])
men_2 = men.children.create(category: "ジャケット/アウター")
men_2.children.create([{category: "テーラードジャケット"},{category: "Gジャン/デニムジャケット"},{category: "レザージャケット"},{category: "ダウンジャケット"},{category: "ライダースジャケット"},{category: "ミリタリージャケット"},{category: "ナイロンジャケット"},{category: "ダッフルコート"},{category: "ピーコート"},{category: "ステンカラーコート"},{category: "トレンチコート"},{category: "モッズコート"},{category: "チェスターコート"},{category: "スカジャン"},{category: "ブルゾン"},{category: "マウンテンパーカー"},{category: "ダウンベスト"},{category: "その他"}])
men_3 = men.children.create(category: "パンツ")
men_3.children.create([{category: "デニム/ジーンズ"},{category: "ワークパンツ/カーゴパンツ"},{category: "スラックス"},{category: "チノパン"},{category: "ショートパンツ"},{category: "ペインターパンツ"},{category: "サルエルパンツ"},{category: "オーバーオール"},{category: "その他"}])
men_4 = men.children.create(category: "靴")
men_4.children.create([{category: "スニーカー"},{category: "サンダル"},{category: "ブーツ"},{category: "モカシン"},{category: "ドレス/ビジネス"},{category: "長靴/レインシューズ"},{category: "デッキシューズ"},{category: "その他"}])
men_5 = men.children.create(category: "バッグ")
men_5.children.create([{category: "ショルダーバッグ"},{category: "トートバッグ"},{category: "ボストンバッグ"},{category: "リュック/バックパック"},{category: "ウエストポーチ"},{category: "ボディーバッグ"},{category: "ドラムバッグ"},{category: "ビジネスバッグ"},{category: "トラベルバッグ"},{category: "メッセンジャーバッグ"},{category: "エコバッグ"},{category: "その他"}])
men_6 = men.children.create(category: "スーツ")
men_6.children.create([{category: "スーツジャケット"},{category: "スーツベスト"},{category: "スラックス"},{category: "セットアップ"},{category: "その他"}])
men_7 = men.children.create(category: "帽子")
men_7.children.create([{category: "キャップ"},{category: "ハット"},{category: "ニットキャップ/ビーニー"},{category: "ハンチング/ベレー帽"},{category: "キャスケット"},{category: "サンバイザー"},{category: "その他"}])
men_8 = men.children.create(category: "アクセサリー")
men_8.children.create([{category: "ネックレス"},{category: "ブレスレット"},{category: "バングル/リストバンド"},{category: "リング"},{category: "ピアス(片耳用)"},{category: "ピアス(両耳用)"},{category: "アンクレット"},{category: "その他"}])
men_9 = men.children.create(category: "小物")
men_9.children.create([{category: "長財布"},{category: "折り財布/マネークリップ"},{category: "コインケース/小銭入れ"},{category: "名刺入れ/定期入れ"},{category: "キーケース/キーホルダー"},{category: "ネクタイ"},{category: "手袋"},{category: "マフラー/ストール"},{category: "バンダナ/ハンカチ"},{category: "ネックウォーマー"},{category: "ベルト/サスペンダー"},{category: "ウォレットチェーン"},{category: "サングラス/メガネ"},{category: "手帳"},{category: "ストラップ"},{category: "ネクタイピン"},{category: "傘"},{category: "レインコート"},{category: "その他"}])
men_10 = men.children.create(category: "時計")
men_10.children.create([{category: "腕時計(アナログ)"},{category: "腕時計(デジタル)"},{category: "ラバーベルト"},{category: "レザーベルト"},{category: "金属ベルト"},{category: "その他"}])
men_11 = men.children.create(category: "水着")
men_11.children.create([{category: "一般水着"},{category: "スポーツ用"},{category: "アクセサリー"},{category: "その他"}])
men_12 = men.children.create(category: "レッグウェア")
men_12.children.create([{category: "ソックス"},{category: "レギンス/スパッツ"},{category: "レッグウォーマー"},{category: "その他"}])
men_13 = men.children.create(category: "アンダーウェア")
men_13.children.create([{category: "トランクス"},{category: "ボクサーパンツ"},{category: "その他"}])
men_14 = men.children.create(category: "その他")
men_14.children.create([{category: "すべて"}])

baby_kids = Category.create(category: "ベビー・キッズ")
baby_kids_1 = baby_kids.children.create(category: "ベビー服(女の子用) ~95cm")
baby_kids_1.children.create([{category: "トップス"},{category: "アウター"},{category: "パンツ"},{category: "スカート"},{category: "ワンピース"},{category: "ベビードレス"},{category: "おくるみ"},{category: "下着/肌着"},{category: "パジャマ"},{category: "ロンパース"},{category: "その他"}])
baby_kids_2 = baby_kids.children.create(category: "ベビー服(男の子用) ~95cm")
baby_kids_2.children.create([{category: "トップス"},{category: "アウター"},{category: "パンツ"},{category: "おくるみ"},{category: "下着/肌着"},{category: "パジャマ"},{category: "ロンパース"},{category: "その他"}])
baby_kids_3 = baby_kids.children.create(category: "ベビー服(男女兼用) ~95cm")
baby_kids_3.children.create([{category: "トップス"},{category: "アウター"},{category: "パンツ"},{category: "おくるみ"},{category: "下着/肌着"},{category: "パジャマ"},{category: "ロンパース"},{category: "その他"}])
baby_kids_4 = baby_kids.children.create(category: "キッズ服(女の子用) 100cm~")
baby_kids_4.children.create([{category: "コート"},{category: "ジャケット/上着"},{category: "トップス(Tシャツ/カットソー)"},{category: "トップス(トレーナー)"},{category: "トップス(チュニック)"},{category: "トップス(タンクトップ)"},{category: "トップス(その他)"},{category: "スカート"},{category: "パンツ"},{category: "ワンピース"},{category: "セットアップ"},{category: "パジャマ"},{category: "フォーマル/ドレス"},{category: "和服"},{category: "浴衣"},{category: "甚平"},{category: "水着"},{category: "その他"}])
baby_kids_5 = baby_kids.children.create(category: "キッズ服(男の子用) 100cm~")
baby_kids_5.children.create([{category: "コート"},{category: "ジャケット/上着"},{category: "トップス(Tシャツ/カットソー)"},{category: "トップス(トレーナー)"},{category: "トップス(その他)"},{category: "パンツ"},{category: "セットアップ"},{category: "パジャマ"},{category: "フォーマル/ドレス"},{category: "和服"},{category: "浴衣"},{category: "甚平"},{category: "水着"},{category: "その他"}])
baby_kids_6 = baby_kids.children.create(category: "キッズ服(男女兼用) 100cm~")
baby_kids_6.children.create([{category: "コート"},{category: "ジャケット/上着"},{category: "トップス(Tシャツ/カットソー)"},{category: "トップス(トレーナー)"},{category: "トップス(その他)"},{category: "ボトムス"},{category: "パジャマ"},{category: "その他"}])
baby_kids_7 = baby_kids.children.create(category: "キッズ靴")
baby_kids_7.children.create([{category: "スニーカー"},{category: "サンダル"},{category: "ブーツ"},{category: "長靴"},{category: "その他"}])
baby_kids_8 = baby_kids.children.create(category: "子ども用ファッション小物")
baby_kids_8.children.create([{category: "靴下/スパッツ"},{category: "帽子"},{category: "エプロン"},{category: "サスペンダー"},{category: "タイツ"},{category: "ハンカチ"},{category: "バンダナ"},{category: "ベルト"},{category: "マフラー"},{category: "傘"},{category: "手袋"},{category: "バッグ"},{category: "その他"}])
baby_kids_9 = baby_kids.children.create(category: "おむつ/トイレ/バス")
baby_kids_9.children.create([{category: "おむつ用品"},{category: "おまる/補助便座"},{category: "トレーニングパンツ"},{category: "ベビーバス"},{category: "お風呂用品"},{category: "その他"}])
baby_kids_10 = baby_kids.children.create(category: "外出/移動用品")
baby_kids_10.children.create([{category: "ベビーカー"},{category: "抱っこひも/スリング"},{category: "チャイルドシート"},{category: "その他"}])
baby_kids_11 = baby_kids.children.create(category: "授乳/食事")
baby_kids_11.children.create([{category: "ミルク"},{category: "ベビーフード"},{category: "ベビー用食器"},{category: "その他"}])
baby_kids_12 = baby_kids.children.create(category: "ベビー家具/寝具/室内用品")
baby_kids_12.children.create([{category: "ベッド"},{category: "布団/毛布"},{category: "イス"},{category: "たんす"},{category: "その他"}])
baby_kids_13 = baby_kids.children.create(category: "おもちゃ")
baby_kids_13.children.create([{category: "おふろのおもちゃ"},{category: "がらがら"},{category: "オルゴール"},{category: "ベビージム"},{category: "手押し車/カタカタ"},{category: "知育玩具"},{category: "その他"}])
baby_kids_14 = baby_kids.children.create(category: "行事/記念品")
baby_kids_14.children.create([{category: "お宮参り用品"},{category: "お食い初め用品"},{category: "アルバム"},{category: "手形/足形"},{category: "その他"}])
baby_kids_15 = baby_kids.children.create(category: "その他")
baby_kids_15.children.create([{category: "母子手帳用品"},{category: "その他"}])

interior_residence_accessory = Category.create(category: "インテリア・住まい・小物")
interior_residence_accessory_1 = interior_residence_accessory.children.create(category: "キッチン/食器")
interior_residence_accessory_1.children.create([{category: "食器"},{category: "調理器具"},{category: "収納/キッチン雑貨"},{category: "弁当用品"},{category: "カトラリー(スプーン等)"},{category: "テーブル用品"},{category: "容器"},{category: "エプロン"},{category: "アルコールグッズ"},{category: "浄水機"},{category: "その他"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(category: "ベッド/マットレス")
interior_residence_accessory_2.children.create([{category: "セミシングルベッド"},{category: "シングルベッド"},{category: "セミダブルベッド"},{category: "ダブルベッド"},{category: "ワイドダブルベッド"},{category: "クイーンベッド"},{category: "キングベッド"},{category: "脚付きマットレスベッド"},{category: "マットレス"},{category: "すのこベッド"},{category: "ロフトベッド/システムベッド"},{category: "簡易ベッド/折りたたみベッド"},{category: "収納付き"},{category: "その他"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(category: "ソファ/ソファベッド")
interior_residence_accessory_3.children.create([{category: "ソファセット"},{category: "シングルソファ"},{category: "ラブソファ"},{category: "トリプルソファ"},{category: "オットマン"},{category: "コーナーソファ"},{category: "ビーズソファ/クッションソファ"},{category: "ローソファ/フロアソファ"},{category: "ソファベッド"},{category: "応接セット"},{category: "ソファカバー"},{category: "リクライニングソファ"},{category: "その他"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(category: "椅子/チェア")
interior_residence_accessory_4.children.create([{category: "一般"},{category: "スツール"},{category: "ダイニングチェア"},{category: "ハイバックチェア"},{category: "ロッキングチェア"},{category: "座椅子"},{category: "折り畳みイス"},{category: "デスクチェア"},{category: "その他"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(category: "机/テーブル")
interior_residence_accessory_5.children.create([{category: "こたつ"},{category: "カウンターテーブル"},{category: "サイドテーブル"},{category: "センターテーブル"},{category: "ダイニングテーブル"},{category: "座卓/ちゃぶ台"},{category: "アウトドア用"},{category: "パソコン用"},{category: "事務机/学習机"},{category: "その他"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(category: "収納家具")
interior_residence_accessory_6.children.create([{category: "リビング収納"},{category: "キッチン収納"},{category: "玄関/屋外収納"},{category: "バス/トイレ収納"},{category: "本収納"},{category: "本/CD/DVD収納"},{category: "洋服タンス/押入れ収納"},{category: "電話台/ファックス台"},{category: "ドレッサー/鏡台"},{category: "棚/ラック"},{category: "ケース/ボックス"},{category: "その他"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(category: "ラグ/カーペット/マット")
interior_residence_accessory_7.children.create([{category: "ラグ"},{category: "カーペット"},{category: "ホットカーペット"},{category: "玄関/キッチンマット"},{category: "トイレ/バスマット"},{category: "その他"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(category: "カーテン/ブラインド")
interior_residence_accessory_8.children.create([{category: "カーテン"},{category: "ブラインド"},{category: "ロールスクリーン"},{category: "のれん"},{category: "その他"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(category: "ライト/照明")
interior_residence_accessory_9.children.create([{category: "蛍光灯/電球"},{category: "天井照明"},{category: "フロアスタンド"},{category: "その他"}])
interior_residence_accessory_10 = interior_residence_accessory.children.create(category: "寝具")
interior_residence_accessory_10.children.create([{category: "布団/毛布"},{category: "枕"},{category: "シーツ/カバー"},{category: "その他"}])
interior_residence_accessory_11 = interior_residence_accessory.children.create(category: "インテリア小物")
interior_residence_accessory_11.children.create([{category: "ごみ箱"},{category: "ウェルカムボード"},{category: "オルゴール"},{category: "クッション/クッションカバー"},{category: "スリッパラック"},{category: "ティッシュボックス"},{category: "バスケット/かご"},{category: "フォトフレーム"},{category: "モビール"},{category: "花瓶"},{category: "灰皿"},{category: "傘立て"},{category: "小物入れ"},{category: "置時計"},{category: "掛時計/柱時計"},{category: "鏡(立て掛け式)"},{category: "鏡(壁掛け式)"},{category: "置物/風鈴"},{category: "植物/観葉植物"},{category: "その他"}])
interior_residence_accessory_12 = interior_residence_accessory.children.create(category: "季節/年中行事")
interior_residence_accessory_12.children.create([{category: "正月"},{category: "成人式"},{category: "バレンタインデー"},{category: "ひな祭り"},{category: "子どもの日"},{category: "母の日"},{category: "父の日"},{category: "父の日"},{category: "サマーギフト/お中元"},{category: "夏/夏休み"},{category: "ハロウィン"},{category: "敬老の日"},{category: "七五三"},{category: "お歳暮"},{category: "クリスマス"},{category: "冬一般"},{category: "その他"}])
interior_residence_accessory_13 = interior_residence_accessory.children.create(category: "その他")
interior_residence_accessory_13.children.create([{category: "すべて"}])

book_music_game = Category.create(category: "本・音楽・ゲーム")
book_music_game_1 = book_music_game.children.create(category: "本")
book_music_game_1.children.create([{category: "文学/小説"},{category: "人文/社会"},{category: "ノンフィクション/教養"},{category: "地図/旅行ガイド"},{category: "ビジネス/経済"},{category: "ビジネス/経済"},{category: "健康/医学"},{category: "コンピュータ/IT"},{category: "趣味/スポーツ/実用"},{category: "住まい/暮らし/子育て"},{category: "アート/エンタメ"},{category: "洋書"},{category: "絵本"},{category: "参考書"},{category: "その他"}])
book_music_game_2 = book_music_game.children.create(category: "漫画")
book_music_game_2.children.create([{category: "全巻セット"},{category: "少年漫画"},{category: "少女漫画"},{category: "青年漫画"},{category: "女性漫画"},{category: "同人誌"},{category: "その他"}])
book_music_game_3 = book_music_game.children.create(category: "雑誌")
book_music_game_3.children.create([{category: "アート/エンタメ/ホビー"},{category: "ファッション"},{category: "ニュース/総合"},{category: "趣味/スポーツ"},{category: "その他"}])
book_music_game_4 = book_music_game.children.create(category: "CD")
book_music_game_4.children.create([{category: "邦楽"},{category: "洋楽"},{category: "アニメ"},{category: "クラシック"},{category: "K-POP/アジア"},{category: "キッズ/ファミリー"},{category: "その他"}])
book_music_game_5 = book_music_game.children.create(category: "DVD/ブルーレイ")
book_music_game_5.children.create([{category: "外国映画"},{category: "日本映画"},{category: "アニメ"},{category: "TVドラマ"},{category: "ミュージック"},{category: "お笑い/バラエティ"},{category: "スポーツ/フィットネス"},{category: "キッズ/ファミリー"},{category: "その他"}])
book_music_game_6 = book_music_game.children.create(category: "レコード")
book_music_game_6.children.create([{category: "邦楽"},{category: "洋楽"},{category: "その他"}])
book_music_game_7 = book_music_game.children.create(category: "テレビゲーム")
book_music_game_7.children.create([{category: "家庭用ゲーム本体"},{category: "家庭用ゲームソフト"},{category: "携帯用ゲーム本体"},{category: "携帯用ゲームソフト"},{category: "PCゲーム"},{category: "その他"}])

toy_hobby_goods = Category.create(category: "おもちゃ・ホビー・グッズ")
toy_hobby_goods_1 = toy_hobby_goods.children.create(category: "おもちゃ")
toy_hobby_goods_1.children.create([{category: "キャラクターグッズ"},{category: "ぬいぐるみ"},{category: "小物/アクセサリー"},{category: "模型/プラモデル"},{category: "ミニカー"},{category: "トイラジコン"},{category: "プラモデル"},{category: "ホビーラジコン"},{category: "鉄道模型"},{category: "その他"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(category: "タレントグッズ")
toy_hobby_goods_2.children.create([{category: "アイドル"},{category: "ミュージシャン"},{category: "タレント/お笑い芸人"},{category: "スポーツ選手"},{category: "その他"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(category: "コミック/アニメグッズ")
toy_hobby_goods_3.children.create([{category: "ストラップ"},{category: "キーホルダー"},{category: "バッジ"},{category: "カード"},{category: "クリアファイル"},{category: "ポスター"},{category: "タオル"},{category: "その他"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(category: "トレーディングカード")
toy_hobby_goods_4.children.create([{category: "遊戯王"},{category: "マジック：ザ・ギャザリング"},{category: "ポケモンカードゲーム"},{category: "デュエルマスターズ"},{category: "バトルスピリッツ"},{category: "プリパラ"},{category: "アイカツ"},{category: "カードファイト!! ヴァンガード"},{category: "ヴァイスシュヴァルツ"},{category: "プロ野球オーナーズリーグ"},{category: "ベースボールヒーローズ"},{category: "ドラゴンボール"},{category: "スリーブ"},{category: "その他"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(category: "フィギュア")
toy_hobby_goods_5.children.create([{category: "コミック/アニメ"},{category: "特撮"},{category: "ゲームキャラクター"},{category: "SF/ファンタジー/ホラー"},{category: "アメコミ"},{category: "スポーツ"},{category: "ミリタリー"},{category: "その他"}])
toy_hobby_goods_6 = toy_hobby_goods.children.create(category: "楽器/器材")
toy_hobby_goods_6.children.create([{category: "エレキギター"},{category: "アコースティックギター"},{category: "ベース"},{category: "エフェクター"},{category: "アンプ"},{category: "弦楽器"},{category: "管楽器"},{category: "鍵盤楽器"},{category: "打楽器"},{category: "和楽器"},{category: "楽譜/スコア"},{category: "レコーディング/PA機器"},{category: "DJ機器"},{category: "DTM/DAW"},{category: "その他"}])
toy_hobby_goods_7 = toy_hobby_goods.children.create(category: "コレクション")
toy_hobby_goods_7.children.create([{category: "武具"},{category: "使用済切手/官製はがき"},{category: "旧貨幣/金貨/銀貨/記念硬貨"},{category: "印刷物"},{category: "ノベルティグッズ"},{category: "その他"}])
toy_hobby_goods_8 = toy_hobby_goods.children.create(category: "ミリタリー")
toy_hobby_goods_8.children.create([{category: "トイガン"},{category: "個人装備"},{category: "その他"}])
toy_hobby_goods_9 = toy_hobby_goods.children.create(category: "美術品")
toy_hobby_goods_9.children.create([{category: "陶芸"},{category: "ガラス"},{category: "漆芸"},{category: "金属工芸"},{category: "絵画/タペストリ"},{category: "版画"},{category: "彫刻/オブジェクト"},{category: "書"},{category: "写真"},{category: "その他"}])
toy_hobby_goods_10 = toy_hobby_goods.children.create(category: "アート用品")
toy_hobby_goods_10.children.create([{category: "画材"},{category: "額縁"},{category: "その他"}])
toy_hobby_goods_11 = toy_hobby_goods.children.create(category: "その他")
toy_hobby_goods_11.children.create([{category: "トランプ/UNO"},{category: "カルタ/百人一首"},{category: "ダーツ"},{category: "ビリヤード"},{category: "麻雀"},{category: "パズル/ジグソーパズル"},{category: "囲碁/将棋"},{category: "オセロ/チェス"},{category: "人生ゲーム"},{category: "野球/サッカーゲーム"},{category: "スポーツ"},{category: "三輪車/乗り物"},{category: "ヨーヨー"},{category: "模型製作用品"},{category: "鉄道"},{category: "航空機"},{category: "アマチュア無線"},{category: "パチンコ/パチスロ"},{category: "その他"}])

cosme_perfume_beauty = Category.create(category: "コスメ・香水・美容")
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(category: "ベースメイク")
cosme_perfume_beauty_1.children.create([{category: "ファンデーション"},{category: "化粧下地"},{category: "コントロールカラー"},{category: "BBクリーム"},{category: "CCクリーム"},{category: "コンシーラー"},{category: "フェイスパウダー"},{category: "トライアルセット/サンプル"},{category: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(category: "メイクアップ")
cosme_perfume_beauty_2.children.create([{category: "アイシャドウ"},{category: "口紅"},{category: "リップグロス"},{category: "リップライナー"},{category: "チーク"},{category: "フェイスカラー"},{category: "マスカラ"},{category: "アイライナー"},{category: "つけまつげ"},{category: "アイブロウペンシル"},{category: "パウダーアイブロウ"},{category: "眉マスカラ"},{category: "トライアルセット/サンプル"},{category: "メイク道具/化粧小物"},{category: "美顔用品/美顔ローラー"},{category: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(category: "ネイルケア")
cosme_perfume_beauty_3.children.create([{category: "ネイルカラー"},{category: "カラージェル"},{category: "ネイルベースコート/トップコート"},{category: "ネイルアート用品"},{category: "ネイルパーツ"},{category: "ネイルチップ/付け爪"},{category: "手入れ用具"},{category: "除光液"},{category: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(category: "香水")
cosme_perfume_beauty_4.children.create([{category: "香水(女性用)"},{category: "香水(男性用)"},{category: "ユニセックス"},{category: "ボディミスト"},{category: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(category: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{category: "化粧水/ローション"},{category: "乳液/ミルク"},{category: "美容液"},{category: "フェイスクリーム"},{category: "洗顔料"},{category: "クレンジング/メイク落とし"},{category: "パック/フェイスマスク"},{category: "ジェル/ゲル"},{category: "ブースター/導入液"},{category: "アイケア"},{category: "リップケア"},{category: "トライアルセット/サンプル"},{category: "洗顔グッズ"},{category: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(category: "ヘアケア")
cosme_perfume_beauty_6.children.create([{category: "シャンプー"},{category: "トリートメント"},{category: "コンディショナー"},{category: "リンス"},{category: "スタイリング剤"},{category: "カラーリング剤"},{category: "ブラシ"},{category: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(category: "ボディケア")
cosme_perfume_beauty_7.children.create([{category: "オイル/クリーム"},{category: "ハンドクリーム"},{category: "ローション"},{category: "日焼け止め/サンオイル"},{category: "ボディソープ"},{category: "入浴剤"},{category: "制汗/デオドラント"},{category: "フットケア"},{category: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(category: "オーラルケア")
cosme_perfume_beauty_8.children.create([{category: "口臭防止/エチケット用品"},{category: "歯ブラシ"},{category: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(category: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{category: "エッセンシャルオイル"},{category: "芳香器"},{category: "お香/香炉"},{category: "キャンドル"},{category: "リラクゼーショングッズ"},{category: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(category: "ダイエット")
cosme_perfume_beauty_10.children.create([{category: "ダイエット食品"},{category: "エクササイズ用品"},{category: "体重計"},{category: "体脂肪計"},{category: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(category: "その他")
cosme_perfume_beauty_11.children.create([{category: "健康用品"},{category: "看護/介護用品"},{category: "救急/衛生用品"},{category: "その他"}])

appliance_smartphone_camera = Category.create(category: "家電・スマホ・カメラ")
appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(category: "スマートフォン/携帯電話")
appliance_smartphone_camera_1.children.create([{category: "スマートフォン本体"},{category: "バッテリー/充電器"},{category: "携帯電話本体"},{category: "PHS本体"},{category: "その他"}])
appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(category: "スマホアクセサリー")
appliance_smartphone_camera_2.children.create([{category: "Android用ケース"},{category: "iPhone用ケース"},{category: "カバー"},{category: "イヤホンジャック"},{category: "ストラップ"},{category: "フィルム"},{category: "自撮り棒"},{category: "その他"}])
appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(category: "PC/タブレット")
appliance_smartphone_camera_3.children.create([{category: "タブレット"},{category: "ノートPC"},{category: "デスクトップ型PC"},{category: "ディスプレイ"},{category: "電子ブックリーダー"},{category: "PC周辺機器"},{category: "PCパーツ"},{category: "その他"}])
appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(category: "カメラ")
appliance_smartphone_camera_4.children.create([{category: "デジタルカメラ"},{category: "ビデオカメラ"},{category: "レンズ(単焦点)"},{category: "レンズ(ズーム)"},{category: "フィルムカメラ"},{category: "防犯カメラ"},{category: "その他"}])
appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(category: "テレビ/映像機器")
appliance_smartphone_camera_5.children.create([{category: "テレビ"},{category: "プロジェクター"},{category: "ブルーレイレコーダー"},{category: "DVDレコーダー"},{category: "ブルーレイプレーヤー"},{category: "DVDプレーヤー"},{category: "映像用ケーブル"},{category: "その他"}])
appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(category: "オーディオ機器")
appliance_smartphone_camera_6.children.create([{category: "ポータブルプレーヤー"},{category: "イヤフォン"},{category: "ヘッドフォン"},{category: "アンプ"},{category: "スピーカー"},{category: "ケーブル/シールド"},{category: "ラジオ"},{category: "その他"}])
appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(category: "美容/健康")
appliance_smartphone_camera_7.children.create([{category: "ヘアドライヤー"},{category: "ヘアアイロン"},{category: "美容機器"},{category: "電気シェーバー"},{category: "電動歯ブラシ"},{category: "その他"}])
appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(category: "冷暖房/空調")
appliance_smartphone_camera_8.children.create([{category: "エアコン"},{category: "空気清浄器"},{category: "加湿器"},{category: "扇風機"},{category: "除湿機"},{category: "ファンヒーター"},{category: "電気ヒーター"},{category: "オイルヒーター"},{category: "ストーブ"},{category: "ホットカーペット"},{category: "こたつ"},{category: "電気毛布"},{category: "その他"}])
appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(category: "生活家電")
appliance_smartphone_camera_9.children.create([{category: "冷蔵庫"},{category: "洗濯機"},{category: "炊飯器"},{category: "電子レンジ/オーブン"},{category: "調理機器"},{category: "アイロン"},{category: "掃除機"},{category: "エスプレッソマシン"},{category: "コーヒーメーカー"},{category: "衣類乾燥機"},{category: "その他"}])
appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(category: "その他")
appliance_smartphone_camera_10.children.create([{category: "その他"}])

sport_leisure = Category.create(category: "スポーツ・レジャー")
sport_leisure_1 = sport_leisure.children.create(category: "ゴルフ")
sport_leisure_1.children.create([{category: "クラブ"},{category: "ウエア(男性用)"},{category: "ウエア(女性用)"},{category: "バッグ"},{category: "シューズ(男性用)"},{category: "シューズ(女性用)"},{category: "アクセサリー"},{category: "その他"}])
sport_leisure_2 = sport_leisure.children.create(category: "フィッシング")
sport_leisure_2.children.create([{category: "ロッド"},{category: "リール"},{category: "ルアー用品"},{category: "ウエア"},{category: "釣り糸/ライン"},{category: "その他"}])
sport_leisure_3 = sport_leisure.children.create(category: "自転車")
sport_leisure_3.children.create([{category: "自転車本体"},{category: "ウエア"},{category: "パーツ"},{category: "アクセサリー"},{category: "バッグ"},{category: "工具/メンテナンス"},{category: "その他"}])
sport_leisure_4 = sport_leisure.children.create(category: "トレーニング/エクササイズ")
sport_leisure_4.children.create([{category: "ランニング"},{category: "ウォーキング"},{category: "ヨガ"},{category: "トレーニング用品"},{category: "その他"}])
sport_leisure_5 = sport_leisure.children.create(category: "野球")
sport_leisure_5.children.create([{category: "ウェア"},{category: "シューズ"},{category: "グローブ"},{category: "バット"},{category: "アクセサリー"},{category: "防具"},{category: "練習機器"},{category: "記念グッズ"},{category: "応援グッズ"},{category: "その他"}])
sport_leisure_6 = sport_leisure.children.create(category: "サッカー/フットサル")
sport_leisure_6.children.create([{category: "ウェア"},{category: "シューズ"},{category: "ボール"},{category: "アクセサリー"},{category: "記念グッズ"},{category: "応援グッズ"},{category: "その他"}])
sport_leisure_7 = sport_leisure.children.create(category: "テニス")
sport_leisure_7.children.create([{category: "ラケット(硬式用)"},{category: "ラケット(軟式用)"},{category: "ウェア"},{category: "シューズ"},{category: "ボール"},{category: "アクセサリー"},{category: "記念グッズ"},{category: "応援グッズ"},{category: "その他"}])
sport_leisure_8 = sport_leisure.children.create(category: "スノーボード")
sport_leisure_8.children.create([{category: "ボード"},{category: "バインディング"},{category: "ブーツ(男性用)"},{category: "ブーツ(女性用)"},{category: "ブーツ(子ども用)"},{category: "ウエア/装備(男性用)"},{category: "ウエア/装備(女性用)"},{category: "ウエア/装備(子ども用)"},{category: "アクセサリー"},{category: "バッグ"},{category: "その他"}])
sport_leisure_9 = sport_leisure.children.create(category: "スキー")
sport_leisure_9.children.create([{category: "板"},{category: "ブーツ(男性用)"},{category: "ブーツ(女性用)"},{category: "ブーツ(子ども用)"},{category: "ビンディング"},{category: "ウエア(男性用)"},{category: "ウエア(女性用)"},{category: "ウエア(子ども用)"},{category: "ストック"},{category: "その他"}])
sport_leisure_10 = sport_leisure.children.create(category: "その他スポーツ")
sport_leisure_10.children.create([{category: "ダンス/バレエ"},{category: "サーフィン"},{category: "バスケットボール"},{category: "バドミントン"},{category: "バレーボール"},{category: "スケートボード"},{category: "陸上競技"},{category: "ラグビー"},{category: "アメリカンフットボール"},{category: "ボクシング"},{category: "ボウリング"},{category: "その他"}])
sport_leisure_11 = sport_leisure.children.create(category: "アウトドア")
sport_leisure_11.children.create([{category: "テント/タープ"},{category: "ライト/ランタン"},{category: "寝袋/寝具"},{category: "テーブル/チェア"},{category: "ストーブ/コンロ"},{category: "調理器具"},{category: "食器"},{category: "登山用品"},{category: "その他"}])
sport_leisure_12 = sport_leisure.children.create(category: "その他")
sport_leisure_12.children.create([{category: "旅行用品"},{category: "その他"}])

handmade = Category.create(category: "ハンドメイド")
handmade_1 = handmade.children.create(category: "アクセサリー(女性用)")
handmade_1.children.create([{category: "ピアス"},{category: "イヤリング"},{category: "ネックレス"},{category: "ブレスレット"},{category: "リング"},{category: "チャーム"},{category: "ヘアゴム"},{category: "アンクレット"},{category: "その他"}])
handmade_2 = handmade.children.create(category: "ファッション/小物")
handmade_2.children.create([{category: "バッグ(女性用)"},{category: "バッグ(男性用)"},{category: "財布(女性用)"},{category: "財布(男性用)"},{category: "ファッション雑貨"},{category: "その他"}])
handmade_3 = handmade.children.create(category: "アクセサリー/時計")
handmade_3.children.create([{category: "アクセサリー(男性用)"},{category: "時計(女性用)"},{category: "時計(男性用)"},{category: "その他"}])
handmade_4 = handmade.children.create(category: "日用品/インテリア")
handmade_4.children.create([{category: "キッチン用品"},{category: "家具"},{category: "文房具"},{category: "アート/写真"},{category: "アロマ/キャンドル"},{category: "フラワー/ガーデン"},{category: "その他"}])
handmade_5 = handmade.children.create(category: "趣味/おもちゃ")
handmade_5.children.create([{category: "クラフト/布製品"},{category: "おもちゃ/人形"},{category: "その他"}])
handmade_6 = handmade.children.create(category: "キッズ/ベビー")
handmade_6.children.create([{category: "ファッション雑貨"},{category: "スタイ/よだれかけ"},{category: "外出用品"},{category: "ネームタグ"},{category: "その他"}])
handmade_7 = handmade.children.create(category: "素材/材料")
handmade_7.children.create([{category: "各種パーツ"},{category: "生地/糸"},{category: "型紙/パターン"},{category: "その他"}])
handmade_8 = handmade.children.create(category: "二次創作物")
handmade_8.children.create([{category: "Ingress"},{category: "クリエイターズ宇宙兄弟"},{category: "その他"},{category: "チケット"},{category: "すべて"}])
handmade_9 = handmade.children.create(category: "その他")
handmade_9.children.create([{category: "すべて"}])

ticket = Category.create(category: "チケット")
ticket_1 = ticket.children.create(category: "音楽")
ticket_1.children.create([{category: "男性アイドル"},{category: "女性アイドル"},{category: "韓流"},{category: "国内アーティスト"},{category: "海外アーティスト"},{category: "音楽フェス"},{category: "声優/アニメ"},{category: "その他"}])
ticket_2 = ticket.children.create(category: "スポーツ")
ticket_2.children.create([{category: "サッカー"},{category: "野球"},{category: "テニス"},{category: "格闘技/プロレス"},{category: "相撲/武道"},{category: "ゴルフ"},{category: "バレーボール"},{category: "バスケットボール"},{category: "モータースポーツ"},{category: "ウィンタースポーツ"},{category: "その他"}])
ticket_3 = ticket.children.create(category: "演劇/芸能")
ticket_3.children.create([{category: "ミュージカル"},{category: "演劇"},{category: "伝統芸能"},{category: "落語"},{category: "お笑い"},{category: "オペラ"},{category: "サーカス"},{category: "バレエ"},{category: "その他"}])
ticket_4 = ticket.children.create(category: "イベント")
ticket_4.children.create([{category: "声優/アニメ"},{category: "キッズ/ファミリー"},{category: "トークショー/講演会"},{category: "その他"}])
ticket_5 = ticket.children.create(category: "映画")
ticket_5.children.create([{category: "邦画"},{category: "洋画"},{category: "その他"}])
ticket_6 = ticket.children.create(category: "施設利用券")
ticket_6.children.create([{category: "遊園地/テーマパーク"},{category: "美術館/博物館"},{category: "スキー場"},{category: "ゴルフ場"},{category: "フィットネスクラブ"},{category: "プール"},{category: "ボウリング場"},{category: "水族館"},{category: "動物園"},{category: "その他"}])
ticket_7 = ticket.children.create(category: "優待券/割引券")
ticket_7.children.create([{category: "ショッピング"},{category: "レストラン/食事券"},{category: "フード/ドリンク券"},{category: "宿泊券"},{category: "その他"}])
ticket_8 = ticket.children.create(category: "その他")
ticket_8.children.create([{category: "すべて"}])


car_motorcycle = Category.create(category: "自動車・オートバイ")
car_motorcycle_1 = car_motorcycle.children.create(category: "自動車本体")
car_motorcycle_1.children.create([{category: "国内自動車本体"},{category: "外国自動車本体"}])
car_motorcycle_2 = car_motorcycle.children.create(category: "自動車タイヤ/ホイール")
car_motorcycle_2.children.create([{category: "タイヤ/ホイールセット"},{category: "タイヤ"},{category: "ホイール"},{category: "その他"}])
car_motorcycle_3 = car_motorcycle.children.create(category: "自動車パーツ")
car_motorcycle_3.children.create([{category: "サスペンション"},{category: "ブレーキ"},{category: "外装、エアロパーツ"},{category: "ライト"},{category: "内装品、シート"},{category: "ステアリング"},{category: "マフラー・排気系"},{category: "エンジン、過給器、冷却装置"},{category: "クラッチ、ミッション、駆動系"},{category: "電装品"},{category: "補強パーツ"},{category: "汎用パーツ"},{category: "外国自動車用パーツ"},{category: "その他"}])
car_motorcycle_4 = car_motorcycle.children.create(category: "自動車アクセサリー")
car_motorcycle_4.children.create([{category: "車内アクセサリー"},{category: "カーナビ"},{category: "カーオーディオ"},{category: "車外アクセサリー"},{category: "メンテナンス用品"},{category: "チャイルドシート"},{category: "ドライブレコーダー"},{category: "レーダー探知機"},{category: "カタログ/マニュアル"},{category: "セキュリティ"},{category: "ETC"},{category: "その他"}])
car_motorcycle_5 = car_motorcycle.children.create(category: "オートバイ車体")
car_motorcycle_5.children.create([{category: "すべて"}])
car_motorcycle_6 = car_motorcycle.children.create(category: "オートバイパーツ")
car_motorcycle_6.children.create([{category: "タイヤ"},{category: "マフラー"},{category: "エンジン、冷却装置"},{category: "カウル、フェンダー、外装"},{category: "サスペンション"},{category: "ホイール"},{category: "シート"},{category: "ブレーキ"},{category: "タンク"},{category: "ライト、ウィンカー"},{category: "チェーン、スプロケット、駆動系"},{category: "メーター"},{category: "電装系"},{category: "ミラー"},{category: "外国オートバイ用パーツ"},{category: "その他"}])
car_motorcycle_7 = car_motorcycle.children.create(category: "オートバイアクセサリー")
car_motorcycle_7.children.create([{category: "ヘルメット/シールド"},{category: "バイクウエア/装備"},{category: "アクセサリー"},{category: "メンテナンス"},{category: "カタログ/マニュアル"},{category: "その他"}])

others = Category.create(category: "その他")
others_1 = others.children.create(category: "まとめ売り")
others_1.children.create([{category: "すべて"}])
others_2 = others.children.create(category: "ペット用品")
others_2.children.create([{category: "ペットフード"},{category: "犬用品"},{category: "猫用品"},{category: "魚用品/水草"},{category: "小動物用品"},{category: "爬虫類/両生類用品"},{category: "かご/おり"},{category: "鳥用品"},{category: "虫類用品"},{category: "その他"}])
others_3 = others.children.create(category: "食品")
others_3.children.create([{category: "菓子"},{category: "米"},{category: "野菜"},{category: "果物"},{category: "調味料"},{category: "魚介類(加工食品)"},{category: "肉類(加工食品)"},{category: "その他 加工食品"},{category: "その他"}])
others_4 = others.children.create(category: "飲料/酒")
others_4.children.create([{category: "コーヒー"},{category: "ソフトドリンク"},{category: "ミネラルウォーター"},{category: "茶"},{category: "ウイスキー"},{category: "ワイン"},{category: "ブランデー"},{category: "焼酎"},{category: "日本酒"},{category: "ビール、発泡酒"},{category: "その他"}])
others_5 = others.children.create(category: "日用品/生活雑貨/旅行")
others_5.children.create([{category: "タバコグッズ"},{category: "タオル/バス用品"},{category: "日用品/生活雑貨"},{category: "洗剤/柔軟剤"},{category: "旅行用品"},{category: "防災関連グッズ"},{category: "その他"}])
others_6 = others.children.create(category: "アンティーク/コレクション")
others_6.children.create([{category: "雑貨"},{category: "工芸品"},{category: "家具"},{category: "印刷物"},{category: "その他"}])
others_7 = others.children.create(category: "文房具/事務用品")
others_7.children.create([{category: "筆記具"},{category: "ノート/メモ帳"},{category: "テープ/マスキングテープ"},{category: "カレンダー/スケジュール"},{category: "アルバム/スクラップ"},{category: "ファイル/バインダー"},{category: "はさみ/カッター"},{category: "カードホルダー/名刺管理"},{category: "のり/ホッチキス"},{category: "その他"}])
others_8 = others.children.create(category: "事務/店舗用品")
others_8.children.create([{category: "オフィス用品一般"},{category: "オフィス家具"},{category: "店舗用品"},{category: "OA機器"},{category: "ラッピング/包装"},{category: "その他"}])
others_9 = others.children.create(category: "その他")
others_9.children.create([{category: "すべて"}])